name: admin-ui-outcall
namespace: official
version: 1.1.0-5
author: Wazo Team
display_name: Outcalls
min_wazo_version: 18.02
tags:
  - routing
homepage: https://github.com/wazo-pbx/wazo-admin-ui-outcall
depends:
  - name: admin-ui-context
    namespace: official
  - name: admin-ui-trunk
    namespace: official
