name: admin-ui-outcall
namespace: official
version: 1.1.0
author: Wazo Team
display_name: Outcalls
min_wazo_version: 17.17
tags:
  - beta
  - routing
homepage: https://github.com/wazo-pbx/wazo-admin-ui-outcall
