name: admin-ui-outcall
namespace: official
version: 0.0.2
author: Wazo Team
display_name: Outcalls
min_wazo_version: 17.16
tags:
  - beta
  - routing
homepage: https://github.com/wazo-pbx/wazo-admin-ui-outcall
